name: LinkedPortals
description: Link portals to their destinations
author: Torm
main: no.hyp.linkedportals.LinkedPortalsPlugin
api-version: 1.13
version: 2.0.0
permissions:
  linkedPortals:
    description: All permissions. Can delete all portal data.
    default: op
    children: [linkedPortals.link]
  linkedPortals.link:
    description: Link and unlink portals.
    default: op
commands:
  netherportal:
    description: View and link portals.
    permission: linkedPortals.link
